// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as QuickChatService from "./quickchatservice.js";
export {
    QuickChatService
};

export {
    ShortcutValidationResult,
    ShortcutValidationStatus
} from "./models.js";
