// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ShortcutValidationResult is returned by shortcut validation requests.
 */
export class ShortcutValidationResult {
    "Shortcut": string;
    "Status": ShortcutValidationStatus;
    "Message": string;

    /** Creates a new ShortcutValidationResult instance. */
    constructor($$source: Partial<ShortcutValidationResult> = {}) {
        if (!("Shortcut" in $$source)) {
            this["Shortcut"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = ShortcutValidationStatus.$zero;
        }
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ShortcutValidationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutValidationResult($$parsedSource as Partial<ShortcutValidationResult>);
    }
}

/**
 * ShortcutValidationStatus describes realtime shortcut availability.
 */
export enum ShortcutValidationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShortcutValidationAvailable = "available",
    ShortcutValidationConflict = "conflict",
    ShortcutValidationInvalid = "invalid",
};
