// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QuickChatService registers the global quick chat shortcut after Wails has
 * started its platform application, so native hotkey APIs run after AppKit is live.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CurrentShortcut returns the normalized quick chat shortcut currently owned by the service.
 */
export function CurrentShortcut(): $CancellablePromise<string> {
    return $Call.ByID(1258530632);
}

/**
 * UpdateShortcut immediately switches the active quick chat global shortcut.
 */
export function UpdateShortcut(shortcut: string): $CancellablePromise<void> {
    return $Call.ByID(3967974578, shortcut);
}

/**
 * ValidateShortcut reports whether a shortcut is usable without changing the active registration.
 */
export function ValidateShortcut(shortcut: string): $CancellablePromise<$models.ShortcutValidationResult> {
    return $Call.ByID(2332936109, shortcut).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ShortcutValidationResult.createFrom;
