// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view_model$0 from "../../../models/view_model/models.js";

export class ApplyFileSettingsInput {
    "target_dir": string;

    /** Creates a new ApplyFileSettingsInput instance. */
    constructor($$source: Partial<ApplyFileSettingsInput> = {}) {
        if (!("target_dir" in $$source)) {
            this["target_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyFileSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyFileSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyFileSettingsInput($$parsedSource as Partial<ApplyFileSettingsInput>);
    }
}

export class ApplyFileSettingsOutput {

    /** Creates a new ApplyFileSettingsOutput instance. */
    constructor($$source: Partial<ApplyFileSettingsOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyFileSettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyFileSettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplyFileSettingsOutput($$parsedSource as Partial<ApplyFileSettingsOutput>);
    }
}

export class LoadBootstrapInput {

    /** Creates a new LoadBootstrapInput instance. */
    constructor($$source: Partial<LoadBootstrapInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadBootstrapInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadBootstrapInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoadBootstrapInput($$parsedSource as Partial<LoadBootstrapInput>);
    }
}

export class LoadBootstrapOutput {
    "bootstrap": view_model$0.SettingsBootstrap;

    /** Creates a new LoadBootstrapOutput instance. */
    constructor($$source: Partial<LoadBootstrapOutput> = {}) {
        if (!("bootstrap" in $$source)) {
            this["bootstrap"] = (new view_model$0.SettingsBootstrap());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoadBootstrapOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LoadBootstrapOutput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bootstrap" in $$parsedSource) {
            $$parsedSource["bootstrap"] = $$createField0_0($$parsedSource["bootstrap"]);
        }
        return new LoadBootstrapOutput($$parsedSource as Partial<LoadBootstrapOutput>);
    }
}

export class SaveDisplaySettingsInput {
    "font_size": string;

    /** Creates a new SaveDisplaySettingsInput instance. */
    constructor($$source: Partial<SaveDisplaySettingsInput> = {}) {
        if (!("font_size" in $$source)) {
            this["font_size"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveDisplaySettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveDisplaySettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveDisplaySettingsInput($$parsedSource as Partial<SaveDisplaySettingsInput>);
    }
}

export class SaveDisplaySettingsOutput {

    /** Creates a new SaveDisplaySettingsOutput instance. */
    constructor($$source: Partial<SaveDisplaySettingsOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveDisplaySettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveDisplaySettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveDisplaySettingsOutput($$parsedSource as Partial<SaveDisplaySettingsOutput>);
    }
}

export class SaveLocaleSettingsInput {
    "locale": string;
    "language": string;

    /** Creates a new SaveLocaleSettingsInput instance. */
    constructor($$source: Partial<SaveLocaleSettingsInput> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveLocaleSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveLocaleSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveLocaleSettingsInput($$parsedSource as Partial<SaveLocaleSettingsInput>);
    }
}

export class SaveLocaleSettingsOutput {

    /** Creates a new SaveLocaleSettingsOutput instance. */
    constructor($$source: Partial<SaveLocaleSettingsOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveLocaleSettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveLocaleSettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveLocaleSettingsOutput($$parsedSource as Partial<SaveLocaleSettingsOutput>);
    }
}

export class SaveShortcutSettingsInput {
    "quick_chat_shortcut": string;

    /** Creates a new SaveShortcutSettingsInput instance. */
    constructor($$source: Partial<SaveShortcutSettingsInput> = {}) {
        if (!("quick_chat_shortcut" in $$source)) {
            this["quick_chat_shortcut"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveShortcutSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveShortcutSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveShortcutSettingsInput($$parsedSource as Partial<SaveShortcutSettingsInput>);
    }
}

export class SaveShortcutSettingsOutput {
    "quick_chat_shortcut": string;
    "status": string;
    "message": string;

    /** Creates a new SaveShortcutSettingsOutput instance. */
    constructor($$source: Partial<SaveShortcutSettingsOutput> = {}) {
        if (!("quick_chat_shortcut" in $$source)) {
            this["quick_chat_shortcut"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveShortcutSettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveShortcutSettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveShortcutSettingsOutput($$parsedSource as Partial<SaveShortcutSettingsOutput>);
    }
}

export class ValidateShortcutSettingsInput {
    "quick_chat_shortcut": string;

    /** Creates a new ValidateShortcutSettingsInput instance. */
    constructor($$source: Partial<ValidateShortcutSettingsInput> = {}) {
        if (!("quick_chat_shortcut" in $$source)) {
            this["quick_chat_shortcut"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateShortcutSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateShortcutSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidateShortcutSettingsInput($$parsedSource as Partial<ValidateShortcutSettingsInput>);
    }
}

export class ValidateShortcutSettingsOutput {
    "quick_chat_shortcut": string;
    "status": string;
    "message": string;

    /** Creates a new ValidateShortcutSettingsOutput instance. */
    constructor($$source: Partial<ValidateShortcutSettingsOutput> = {}) {
        if (!("quick_chat_shortcut" in $$source)) {
            this["quick_chat_shortcut"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateShortcutSettingsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateShortcutSettingsOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidateShortcutSettingsOutput($$parsedSource as Partial<ValidateShortcutSettingsOutput>);
    }
}

// Private type creation functions
const $$createType0 = view_model$0.SettingsBootstrap.createFrom;
