// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../../pkg/provider/models.js";

export class Language {
    "id": string;
    "name": string;

    /** Creates a new Language instance. */
    constructor($$source: Partial<Language> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Language instance from a string or object.
     */
    static createFrom($$source: any = {}): Language {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Language($$parsedSource as Partial<Language>);
    }
}

export class Model {
    "id": number;
    "provider_id": number;
    "model": string;
    "owned_by": string;
    "object": string;
    "enable": boolean;
    "alias": string | null;
    "is_custom": boolean;

    /**
     * 是否是默认模型
     */
    "is_default": boolean;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("alias" in $$source)) {
            this["alias"] = null;
        }
        if (!("is_custom" in $$source)) {
            this["is_custom"] = false;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

/**
 * Provider is the provider list/detail payload returned to the frontend.
 */
export class Provider {
    "id": number;
    "icon": string;
    "provider_type": provider$0.Type;
    "provider_name": string;
    "base_url": string;
    "enabled": boolean;
    "api_key": string;

    /**
     * 是否是默认供应商
     */
    "is_default": boolean;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = provider$0.Type.$zero;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class ProviderModel {
    "provider": Provider;
    "models": Model[];

    /** Creates a new ProviderModel instance. */
    constructor($$source: Partial<ProviderModel> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = (new Provider());
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderModel instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderModel {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provider" in $$parsedSource) {
            $$parsedSource["provider"] = $$createField0_0($$parsedSource["provider"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField1_0($$parsedSource["models"]);
        }
        return new ProviderModel($$parsedSource as Partial<ProviderModel>);
    }
}

export class Region {
    "icon": string;
    "id": string;
    "name": string;

    /** Creates a new Region instance. */
    constructor($$source: Partial<Region> = {}) {
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Region instance from a string or object.
     */
    static createFrom($$source: any = {}): Region {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Region($$parsedSource as Partial<Region>);
    }
}

/**
 * SettingsBootstrap contains the initial settings payload required by the frontend settings window.
 */
export class SettingsBootstrap {
    "locale": string;
    "language": string;
    "font_size": string;
    "data_dir": string;
    "log_level": string;
    "quick_chat_shortcut": string;
    "default_provider_id": number;
    "version": string;

    /** Creates a new SettingsBootstrap instance. */
    constructor($$source: Partial<SettingsBootstrap> = {}) {
        if (!("locale" in $$source)) {
            this["locale"] = "";
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = "";
        }
        if (!("data_dir" in $$source)) {
            this["data_dir"] = "";
        }
        if (!("log_level" in $$source)) {
            this["log_level"] = "";
        }
        if (!("quick_chat_shortcut" in $$source)) {
            this["quick_chat_shortcut"] = "";
        }
        if (!("default_provider_id" in $$source)) {
            this["default_provider_id"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsBootstrap instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsBootstrap {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsBootstrap($$parsedSource as Partial<SettingsBootstrap>);
    }
}

export class SupportedProvider {
    "type": provider$0.Type;
    "icon": string;
    "name": string;
    "description": string;
    "base_url": string;

    /** Creates a new SupportedProvider instance. */
    constructor($$source: Partial<SupportedProvider> = {}) {
        if (!("type" in $$source)) {
            this["type"] = provider$0.Type.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportedProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportedProvider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportedProvider($$parsedSource as Partial<SupportedProvider>);
    }
}

// Private type creation functions
const $$createType0 = Provider.createFrom;
const $$createType1 = Model.createFrom;
const $$createType2 = $Create.Array($$createType1);
