// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../models/data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as view_models$0 from "../models/view_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../pkg/plugins/models.js";

export function AddMCPToolFromFolder(path: string): $CancellablePromise<view_models$0.Tool | null> {
    return $Call.ByID(2335892937, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function AddPluginFromFolder(path: string): $CancellablePromise<plugins$0.Summary | null> {
    return $Call.ByID(1904122002, path).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * AddProvider 添加供应商
 */
export function AddProvider(provider: view_models$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(2363217024, provider);
}

/**
 * AddProviderCustomModel 添加自定义模型
 */
export function AddProviderCustomModel(providerId: number, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(1808092888, providerId, modelName);
}

export function CallPluginTool(aliasID: string, args: string): $CancellablePromise<string> {
    return $Call.ByID(4084159011, aliasID, args);
}

export function CallPluginToolDirect(pluginID: string, kind: string, toolID: string, args: string): $CancellablePromise<string> {
    return $Call.ByID(3138056594, pluginID, kind, toolID, args);
}

/**
 * ChatInfo 对话信息
 */
export function ChatInfo(chatUuid: string): $CancellablePromise<view_models$0.Chat | null> {
    return $Call.ByID(1668598080, chatUuid).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ChatList 聊天列表
 */
export function ChatList(offset: number, limit: number, keyword: string | null, isCollection: boolean): $CancellablePromise<view_models$0.ChatList | null> {
    return $Call.ByID(1229500932, offset, limit, keyword, isCollection).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ChatMessages 聊天消息
 */
export function ChatMessages(chatUuid: string, offset: number, limit: number): $CancellablePromise<view_models$0.MessageList | null> {
    return $Call.ByID(4205977752, chatUuid, offset, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * CloseFormWindow closes a form window by name. Used by form pages to self-close after submit.
 */
export function CloseFormWindow(name: string): $CancellablePromise<void> {
    return $Call.ByID(1541477940, name);
}

/**
 * CollectionChat 收藏/取消收藏对话
 */
export function CollectionChat(chatUuid: string, isCollection: boolean): $CancellablePromise<void> {
    return $Call.ByID(1162381388, chatUuid, isCollection);
}

export function CompleteOnboarding(provider: view_models$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(1964169468, provider);
}

/**
 * Completions 聊天完成接口，负责参数校验、资源初始化和启动异步任务。
 * 实际的执行逻辑委托给 completionRunner（见 chat_completion_runner.go）。
 */
export function Completions(inputMessage: view_models$0.Message): $CancellablePromise<view_models$0.Completions | null> {
    return $Call.ByID(2526998161, inputMessage).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ConfigureEmbedding 配置嵌入引擎。前端调用此方法传入嵌入配置后，
 * 重建 HybridSearcher 以启用向量搜索。
 */
export function ConfigureEmbedding(provider: string, baseURL: string, apiKey: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(3314821975, provider, baseURL, apiKey, model);
}

/**
 * CreateCustomAgent creates a new custom agent.
 */
export function CreateCustomAgent(input: view_models$0.CustomAgentInput): $CancellablePromise<view_models$0.AgentDetail | null> {
    return $Call.ByID(2169404366, input).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * CreateSkill creates a new skill after validation.
 */
export function CreateSkill(input: view_models$0.SkillDetail): $CancellablePromise<view_models$0.SkillDetail | null> {
    return $Call.ByID(1414931439, input).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * DeleteChat 删除聊天
 */
export function DeleteChat(chatUuid: string): $CancellablePromise<void> {
    return $Call.ByID(2431139091, chatUuid);
}

/**
 * DeleteCustomAgent deletes a custom agent.
 */
export function DeleteCustomAgent(id: string): $CancellablePromise<void> {
    return $Call.ByID(1011731219, id);
}

export function DeleteMCPTool(toolID: string): $CancellablePromise<void> {
    return $Call.ByID(2048187701, toolID);
}

/**
 * DeleteMemory 软删除记忆。
 */
export function DeleteMemory(id: number): $CancellablePromise<void> {
    return $Call.ByID(1846175366, id);
}

export function DeletePlugin(id: string): $CancellablePromise<void> {
    return $Call.ByID(4087264930, id);
}

/**
 * DeleteProvider 删除供应商
 */
export function DeleteProvider(providerId: number): $CancellablePromise<void> {
    return $Call.ByID(1837639636, providerId);
}

export function DeleteProviderCustomModel(providerId: number, modelName: string): $CancellablePromise<void> {
    return $Call.ByID(2573490636, providerId, modelName);
}

/**
 * DeleteSkill removes a skill by name.
 */
export function DeleteSkill(name: string): $CancellablePromise<void> {
    return $Call.ByID(1433770462, name);
}

/**
 * DisableEmbedding 禁用向量搜索，回退到纯 FTS5/LIKE。
 */
export function DisableEmbedding(): $CancellablePromise<void> {
    return $Call.ByID(3229847879);
}

export function DownloadPluginRuntime(): $CancellablePromise<plugins$0.RuntimeStatus | null> {
    return $Call.ByID(3959457651).then(($result: any) => {
        return $$createType17($result);
    });
}

export function ExitApp(): $CancellablePromise<void> {
    return $Call.ByID(125618793);
}

/**
 * GenChatTitle 创建聊天标题
 */
export function GenChatTitle(chatUuid: string, modelId: number, modelName: string, update: boolean): $CancellablePromise<string> {
    return $Call.ByID(726618912, chatUuid, modelId, modelName, update);
}

/**
 * GetAgent 返回指定 Agent 的详情，包含其关联的提示词内容。
 */
export function GetAgent(name: string): $CancellablePromise<view_models$0.AgentDetail | null> {
    return $Call.ByID(675794715, name).then(($result: any) => {
        return $$createType13($result);
    });
}

export function GetAppPreferences(): $CancellablePromise<view_models$0.AppPreferences | null> {
    return $Call.ByID(3272455837).then(($result: any) => {
        return $$createType19($result);
    });
}

export function GetChatActiveTask(chatUuid: string): $CancellablePromise<view_models$0.Task | null> {
    return $Call.ByID(230063095, chatUuid).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetEmbeddingProviders 返回支持的嵌入引擎列表。
 */
export function GetEmbeddingProviders(): $CancellablePromise<{ [_ in string]?: string }[]> {
    return $Call.ByID(168490155).then(($result: any) => {
        return $$createType23($result);
    });
}

export function GetFileInfoByPaths(paths: string[]): $CancellablePromise<view_models$0.FileInfo[]> {
    return $Call.ByID(3358092203, paths).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * GetMemories 分页查询记忆列表。
 */
export function GetMemories(query: view_models$0.MemoryListQuery): $CancellablePromise<view_models$0.MemoryListResponse | null> {
    return $Call.ByID(3713705637, query).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * GetMemoryDetail 获取单条记忆详情。
 */
export function GetMemoryDetail(id: number): $CancellablePromise<view_models$0.Memory | null> {
    return $Call.ByID(1484199416, id).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * GetMemoryStats 获取记忆统计。
 */
export function GetMemoryStats(): $CancellablePromise<view_models$0.MemoryStats | null> {
    return $Call.ByID(3560819144).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * GetModels 获取所有模型
 */
export function GetModels(enableProvider: boolean | null, enableModel: boolean | null): $CancellablePromise<view_models$0.Model[]> {
    return $Call.ByID(2435611672, enableProvider, enableModel).then(($result: any) => {
        return $$createType33($result);
    });
}

export function GetPlugin(id: string): $CancellablePromise<plugins$0.Summary | null> {
    return $Call.ByID(1004248857, id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPluginRuntimeStatus(): $CancellablePromise<plugins$0.RuntimeStatus> {
    return $Call.ByID(900529865).then(($result: any) => {
        return $$createType16($result);
    });
}

export function GetPluginSettings(id: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1239164420, id).then(($result: any) => {
        return $$createType34($result);
    });
}

export function GetPromptFile(name: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(508910466, name).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * GetProviderModels 获取供应商模型信息
 */
export function GetProviderModels(provider: view_models$0.Provider): $CancellablePromise<view_models$0.Model[]> {
    return $Call.ByID(1264152129, provider).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * GetProviders 获取所有供应商
 */
export function GetProviders(): $CancellablePromise<view_models$0.Provider[]> {
    return $Call.ByID(3921712104).then(($result: any) => {
        return $$createType38($result);
    });
}

export function GetRunningTasks(): $CancellablePromise<view_models$0.TaskList | null> {
    return $Call.ByID(2644190933).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * GetSkill returns the full detail of a skill by name.
 */
export function GetSkill(name: string): $CancellablePromise<view_models$0.SkillDetail | null> {
    return $Call.ByID(1291472183, name).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetSupportProviders 获取支持的供应商列表
 */
export function GetSupportProviders(): $CancellablePromise<view_models$0.SupportProvider[]> {
    return $Call.ByID(4035154853).then(($result: any) => {
        return $$createType42($result);
    });
}

export function GetTask(taskUuid: string): $CancellablePromise<view_models$0.Task | null> {
    return $Call.ByID(167956275, taskUuid).then(($result: any) => {
        return $$createType21($result);
    });
}

export function GetTools(): $CancellablePromise<view_models$0.Tool[]> {
    return $Call.ByID(432097153).then(($result: any) => {
        return $$createType43($result);
    });
}

/**
 * ImportSkillsFromFolder scans a folder for .md skill files and imports them.
 */
export function ImportSkillsFromFolder(folderPath: string): $CancellablePromise<view_models$0.SkillSummary[]> {
    return $Call.ByID(376506509, folderPath).then(($result: any) => {
        return $$createType45($result);
    });
}

export function IsInitialized(): $CancellablePromise<boolean> {
    return $Call.ByID(2734665048);
}

/**
 * ListAgents 返回所有已注册 Agent 的摘要信息。
 */
export function ListAgents(): $CancellablePromise<view_models$0.AgentSummary[]> {
    return $Call.ByID(1996549960).then(($result: any) => {
        return $$createType47($result);
    });
}

export function ListPlugins(): $CancellablePromise<plugins$0.Summary[]> {
    return $Call.ByID(579674094).then(($result: any) => {
        return $$createType48($result);
    });
}

export function ListPromptFiles(): $CancellablePromise<view_models$0.PromptFileSummary[]> {
    return $Call.ByID(3509338483).then(($result: any) => {
        return $$createType50($result);
    });
}

/**
 * ListSkills returns a summary list of all available skills.
 */
export function ListSkills(): $CancellablePromise<view_models$0.SkillSummary[]> {
    return $Call.ByID(1487878748).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * OPCClearConversation 清除某个聊天的所有消息（不删除联系人或群聊）
 */
export function OPCClearConversation(chatUuid: string): $CancellablePromise<void> {
    return $Call.ByID(2601657508, chatUuid);
}

export function OPCCreateGroup(input: view_models$0.OPCGroupInput): $CancellablePromise<view_models$0.OPCGroupView | null> {
    return $Call.ByID(35429625, input).then(($result: any) => {
        return $$createType52($result);
    });
}

export function OPCCreatePerson(input: view_models$0.OPCPersonInput): $CancellablePromise<view_models$0.OPCPersonView | null> {
    return $Call.ByID(217156171, input).then(($result: any) => {
        return $$createType54($result);
    });
}

export function OPCDeleteGroup(groupUuid: string): $CancellablePromise<void> {
    return $Call.ByID(1904850228, groupUuid);
}

export function OPCDeletePerson(personUuid: string): $CancellablePromise<void> {
    return $Call.ByID(550074600, personUuid);
}

export function OPCGetGroup(groupUuid: string): $CancellablePromise<view_models$0.OPCGroupView | null> {
    return $Call.ByID(1215794833, groupUuid).then(($result: any) => {
        return $$createType52($result);
    });
}

export function OPCGetPerson(personUuid: string): $CancellablePromise<view_models$0.OPCPersonView | null> {
    return $Call.ByID(3469665795, personUuid).then(($result: any) => {
        return $$createType54($result);
    });
}

/**
 * OPCGroupChat 群聊：发送消息，agents 自主决定是否回复
 */
export function OPCGroupChat(input: view_models$0.OPCGroupCompletionInput): $CancellablePromise<view_models$0.Completions | null> {
    return $Call.ByID(1083905707, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function OPCListGroups(): $CancellablePromise<view_models$0.OPCGroupView[]> {
    return $Call.ByID(1818674966).then(($result: any) => {
        return $$createType55($result);
    });
}

export function OPCListPersons(): $CancellablePromise<view_models$0.OPCPersonView[]> {
    return $Call.ByID(4240679872).then(($result: any) => {
        return $$createType56($result);
    });
}

/**
 * OPCPersonChat 人员私聊：发送消息给指定人员，非流式返回完整回复
 */
export function OPCPersonChat(input: view_models$0.OPCCompletionInput): $CancellablePromise<view_models$0.Completions | null> {
    return $Call.ByID(386058529, input).then(($result: any) => {
        return $$createType11($result);
    });
}

export function OPCSearch(keyword: string): $CancellablePromise<[view_models$0.OPCPersonView[], view_models$0.OPCGroupView[]]> {
    return $Call.ByID(3725378810, keyword).then(($result: any) => {
        $result[0] = $$createType56($result[0]);
        $result[1] = $$createType55($result[1]);
        return $result;
    });
}

export function OPCSelectAvatar(): $CancellablePromise<string> {
    return $Call.ByID(2379289307);
}

export function OPCTogglePinGroup(groupUuid: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(465678536, groupUuid, pinned);
}

export function OPCTogglePinPerson(personUuid: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(1662219716, personUuid, pinned);
}

export function OPCUpdateGroup(input: view_models$0.OPCGroupInput): $CancellablePromise<view_models$0.OPCGroupView | null> {
    return $Call.ByID(2536825506, input).then(($result: any) => {
        return $$createType52($result);
    });
}

export function OPCUpdatePerson(input: view_models$0.OPCPersonInput): $CancellablePromise<view_models$0.OPCPersonView | null> {
    return $Call.ByID(3479873286, input).then(($result: any) => {
        return $$createType54($result);
    });
}

export function OpenAddAgentWindow(): $CancellablePromise<void> {
    return $Call.ByID(1848431590);
}

export function OpenAddProviderWindow(): $CancellablePromise<void> {
    return $Call.ByID(3698690788);
}

export function OpenAddSkillWindow(): $CancellablePromise<void> {
    return $Call.ByID(3423520422);
}

/**
 * OpenEditMemoryWindow opens a per-ID singleton window for editing a memory record.
 * Multiple memories can be edited in parallel; reopening the same id focuses the existing window.
 */
export function OpenEditMemoryWindow(id: number): $CancellablePromise<void> {
    return $Call.ByID(957739905, id);
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(639918028, path);
}

export function OpenPluginSettingsWindow(id: string): $CancellablePromise<void> {
    return $Call.ByID(2089761316, id);
}

export function OpenSettingsAboutWindow(): $CancellablePromise<void> {
    return $Call.ByID(3760936256);
}

export function OpenSettingsWindow(): $CancellablePromise<void> {
    return $Call.ByID(3479182543);
}

export function RegisterFileDropHandler(window: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3107036160, window);
}

/**
 * RenameChat 重命名聊天
 */
export function RenameChat(chatUuid: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(2654224378, chatUuid, title);
}

export function RenderCoreMemorySnapshot(): $CancellablePromise<string> {
    return $Call.ByID(4250668926);
}

/**
 * ResetAgentPrompt 将指定 Agent 的某个提示词恢复为默认内容。
 */
export function ResetAgentPrompt(agentName: string, promptName: string): $CancellablePromise<view_models$0.AgentDetail | null> {
    return $Call.ByID(2502039740, agentName, promptName).then(($result: any) => {
        return $$createType13($result);
    });
}

export function ResetPromptFile(name: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(2827988805, name).then(($result: any) => {
        return $$createType36($result);
    });
}

export function RespondToolApproval(input: data_models$0.ToolApprovalResponse): $CancellablePromise<void> {
    return $Call.ByID(1866640078, input);
}

/**
 * RestoreMemory 恢复已遗忘的记忆。
 */
export function RestoreMemory(id: number): $CancellablePromise<void> {
    return $Call.ByID(1532690763, id);
}

export function SavePluginSettings(id: string, config: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(4272693657, id, config).then(($result: any) => {
        return $$createType34($result);
    });
}

export function SelectFiles(): $CancellablePromise<view_models$0.FileInfo[]> {
    return $Call.ByID(1220601789).then(($result: any) => {
        return $$createType25($result);
    });
}

export function SelectMCPFolder(): $CancellablePromise<string> {
    return $Call.ByID(2243094534);
}

export function SelectPluginFolder(): $CancellablePromise<string> {
    return $Call.ByID(2365611709);
}

/**
 * SelectSkillFolder opens a folder selection dialog for importing skills.
 */
export function SelectSkillFolder(): $CancellablePromise<string> {
    return $Call.ByID(2018289455);
}

/**
 * SetDefaultProvider 设置默认供应商，并返回用于聊天默认选择的模型
 */
export function SetDefaultProvider(providerId: number): $CancellablePromise<view_models$0.Model | null> {
    return $Call.ByID(290801006, providerId).then(($result: any) => {
        return $$createType57($result);
    });
}

export function SetPluginEnabled(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(938826134, id, enabled);
}

export function StopCompletions(messageKey: string): $CancellablePromise<void> {
    return $Call.ByID(115959129, messageKey);
}

export function StopTask(taskUuid: string): $CancellablePromise<void> {
    return $Call.ByID(2829427223, taskUuid);
}

export function TestPluginConnection(id: string, protocol: string, config: { [_ in string]?: any }): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3985021265, id, protocol, config).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * UpdateAgentPrompt 更新指定 Agent 的某个提示词内容。
 */
export function UpdateAgentPrompt(agentName: string, promptName: string, content: string): $CancellablePromise<view_models$0.AgentDetail | null> {
    return $Call.ByID(2219566078, agentName, promptName, content).then(($result: any) => {
        return $$createType13($result);
    });
}

export function UpdateAppPreferences(input: view_models$0.AppPreferences): $CancellablePromise<view_models$0.AppPreferences | null> {
    return $Call.ByID(3440343940, input).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * UpdateCustomAgent updates an existing custom agent.
 */
export function UpdateCustomAgent(input: view_models$0.CustomAgentInput): $CancellablePromise<view_models$0.AgentDetail | null> {
    return $Call.ByID(2794305161, input).then(($result: any) => {
        return $$createType13($result);
    });
}

export function UpdateMCPToolEnabled(toolID: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2043009872, toolID, enabled);
}

/**
 * UpdateMemory 编辑记忆并在可用时自动重建 embedding。
 */
export function UpdateMemory(id: number, input: view_models$0.MemoryUpdateInput): $CancellablePromise<view_models$0.Memory | null> {
    return $Call.ByID(2392322548, id, input).then(($result: any) => {
        return $$createType29($result);
    });
}

export function UpdatePromptFile(name: string, content: string): $CancellablePromise<view_models$0.PromptFileDetail | null> {
    return $Call.ByID(487143775, name, content).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * UpdateProvider 更新供应商
 */
export function UpdateProvider(id: number, provider: view_models$0.Provider | null): $CancellablePromise<void> {
    return $Call.ByID(2109525354, id, provider);
}

/**
 * UpdateProviderModels 更新供应商
 */
export function UpdateProviderModels(providerId: number): $CancellablePromise<void> {
    return $Call.ByID(3054855516, providerId);
}

/**
 * UpdateSkill updates an existing skill.
 */
export function UpdateSkill(name: string, input: view_models$0.SkillDetail): $CancellablePromise<view_models$0.SkillDetail | null> {
    return $Call.ByID(889877976, name, input).then(($result: any) => {
        return $$createType15($result);
    });
}

// Private type creation functions
const $$createType0 = view_models$0.Tool.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = plugins$0.Summary.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = data_models$0.Chat.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = view_models$0.ChatList.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = view_models$0.MessageList.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = view_models$0.Completions.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = view_models$0.AgentDetail.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = view_models$0.SkillDetail.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = plugins$0.RuntimeStatus.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = view_models$0.AppPreferences.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = data_models$0.Task.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $Create.Map($Create.Any, $Create.Any);
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = data_models$0.File.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = view_models$0.MemoryListResponse.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = view_models$0.Memory.createFrom;
const $$createType29 = $Create.Nullable($$createType28);
const $$createType30 = view_models$0.MemoryStats.createFrom;
const $$createType31 = $Create.Nullable($$createType30);
const $$createType32 = view_models$0.Model.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = $Create.Map($Create.Any, $Create.Any);
const $$createType35 = view_models$0.PromptFileDetail.createFrom;
const $$createType36 = $Create.Nullable($$createType35);
const $$createType37 = view_models$0.Provider.createFrom;
const $$createType38 = $Create.Array($$createType37);
const $$createType39 = view_models$0.TaskList.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = view_models$0.SupportProvider.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = $Create.Array($$createType0);
const $$createType44 = view_models$0.SkillSummary.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = view_models$0.AgentSummary.createFrom;
const $$createType47 = $Create.Array($$createType46);
const $$createType48 = $Create.Array($$createType2);
const $$createType49 = view_models$0.PromptFileSummary.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = view_models$0.OPCGroupView.createFrom;
const $$createType52 = $Create.Nullable($$createType51);
const $$createType53 = view_models$0.OPCPersonView.createFrom;
const $$createType54 = $Create.Nullable($$createType53);
const $$createType55 = $Create.Array($$createType51);
const $$createType56 = $Create.Array($$createType53);
const $$createType57 = $Create.Nullable($$createType32);
