// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as data_models$0 from "../data_models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugins$0 from "../../pkg/plugins/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../../../time/models.js";

export class AgentDetail {
    "name": string;
    "display_name": string;
    "description": string;
    "agent_type": string;
    "agent_role": string;
    "prompt_names": string[];
    "is_deletable": boolean;
    "tools": string[];
    "skills": string[];
    "prompts": AgentPrompt[];

    /** Creates a new AgentDetail instance. */
    constructor($$source: Partial<AgentDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("agent_type" in $$source)) {
            this["agent_type"] = "";
        }
        if (!("agent_role" in $$source)) {
            this["agent_role"] = "";
        }
        if (!("prompt_names" in $$source)) {
            this["prompt_names"] = [];
        }
        if (!("is_deletable" in $$source)) {
            this["is_deletable"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }
        if (!("prompts" in $$source)) {
            this["prompts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentDetail {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompt_names" in $$parsedSource) {
            $$parsedSource["prompt_names"] = $$createField5_0($$parsedSource["prompt_names"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField7_0($$parsedSource["tools"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField8_0($$parsedSource["skills"]);
        }
        if ("prompts" in $$parsedSource) {
            $$parsedSource["prompts"] = $$createField9_0($$parsedSource["prompts"]);
        }
        return new AgentDetail($$parsedSource as Partial<AgentDetail>);
    }
}

export class AgentPrompt {
    "name": string;
    "title": string;
    "description": string;
    "content": string;
    "is_system": boolean;

    /** Creates a new AgentPrompt instance. */
    constructor($$source: Partial<AgentPrompt> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentPrompt instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentPrompt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentPrompt($$parsedSource as Partial<AgentPrompt>);
    }
}

export class AgentSummary {
    "name": string;
    "display_name": string;
    "description": string;
    "agent_type": string;
    "agent_role": string;
    "prompt_names": string[];
    "is_deletable": boolean;
    "tools": string[];
    "skills": string[];

    /** Creates a new AgentSummary instance. */
    constructor($$source: Partial<AgentSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_name" in $$source)) {
            this["display_name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("agent_type" in $$source)) {
            this["agent_type"] = "";
        }
        if (!("agent_role" in $$source)) {
            this["agent_role"] = "";
        }
        if (!("prompt_names" in $$source)) {
            this["prompt_names"] = [];
        }
        if (!("is_deletable" in $$source)) {
            this["is_deletable"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentSummary {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prompt_names" in $$parsedSource) {
            $$parsedSource["prompt_names"] = $$createField5_0($$parsedSource["prompt_names"]);
        }
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField7_0($$parsedSource["tools"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField8_0($$parsedSource["skills"]);
        }
        return new AgentSummary($$parsedSource as Partial<AgentSummary>);
    }
}

export class AppPreferences {
    "language": data_models$0.AppLanguage;
    "region": data_models$0.AppRegion;
    "memory_system_enabled": boolean;
    "vector_search_enabled": boolean;
    "embedding_provider": string;
    "embedding_base_url": string;
    "embedding_api_key": string;
    "embedding_model": string;

    /** Creates a new AppPreferences instance. */
    constructor($$source: Partial<AppPreferences> = {}) {
        if (!("language" in $$source)) {
            this["language"] = data_models$0.AppLanguage.$zero;
        }
        if (!("region" in $$source)) {
            this["region"] = data_models$0.AppRegion.$zero;
        }
        if (!("memory_system_enabled" in $$source)) {
            this["memory_system_enabled"] = false;
        }
        if (!("vector_search_enabled" in $$source)) {
            this["vector_search_enabled"] = false;
        }
        if (!("embedding_provider" in $$source)) {
            this["embedding_provider"] = "";
        }
        if (!("embedding_base_url" in $$source)) {
            this["embedding_base_url"] = "";
        }
        if (!("embedding_api_key" in $$source)) {
            this["embedding_api_key"] = "";
        }
        if (!("embedding_model" in $$source)) {
            this["embedding_model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppPreferences instance from a string or object.
     */
    static createFrom($$source: any = {}): AppPreferences {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppPreferences($$parsedSource as Partial<AppPreferences>);
    }
}

export const Chat = data_models$0.Chat;
export type Chat = data_models$0.Chat;

export class ChatList {
    "lists": Chat[];
    "total": number;

    /** Creates a new ChatList instance. */
    constructor($$source: Partial<ChatList> = {}) {
        if (!("lists" in $$source)) {
            this["lists"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatList instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatList {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lists" in $$parsedSource) {
            $$parsedSource["lists"] = $$createField0_0($$parsedSource["lists"]);
        }
        return new ChatList($$parsedSource as Partial<ChatList>);
    }
}

export class Completions {
    "chat_uuid": string;
    "task_uuid": string;
    "message_uuid": string;
    "event_key": string;

    /** Creates a new Completions instance. */
    constructor($$source: Partial<Completions> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("task_uuid" in $$source)) {
            this["task_uuid"] = "";
        }
        if (!("message_uuid" in $$source)) {
            this["message_uuid"] = "";
        }
        if (!("event_key" in $$source)) {
            this["event_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Completions instance from a string or object.
     */
    static createFrom($$source: any = {}): Completions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Completions($$parsedSource as Partial<Completions>);
    }
}

export class CustomAgentInput {
    "id": string;
    "name": string;
    "description": string;
    "prompt": string;
    "tools": string[];
    "skills": string[];

    /** Creates a new CustomAgentInput instance. */
    constructor($$source: Partial<CustomAgentInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomAgentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomAgentInput {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField4_0($$parsedSource["tools"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField5_0($$parsedSource["skills"]);
        }
        return new CustomAgentInput($$parsedSource as Partial<CustomAgentInput>);
    }
}

export const FileInfo = data_models$0.File;
export type FileInfo = data_models$0.File;

export class Memory {
    "id": number;
    "summary": string;
    "content": string;
    "type": string;
    "target": string;
    "source": string;
    "char_count": number;
    "is_forgotten": boolean;
    "recall_count": number;
    "has_embedding": boolean;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;

    /** Creates a new Memory instance. */
    constructor($$source: Partial<Memory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("char_count" in $$source)) {
            this["char_count"] = 0;
        }
        if (!("is_forgotten" in $$source)) {
            this["is_forgotten"] = false;
        }
        if (!("recall_count" in $$source)) {
            this["recall_count"] = 0;
        }
        if (!("has_embedding" in $$source)) {
            this["has_embedding"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Memory instance from a string or object.
     */
    static createFrom($$source: any = {}): Memory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Memory($$parsedSource as Partial<Memory>);
    }
}

export class MemoryListQuery {
    "offset": number;
    "limit": number;
    "keyword": string;
    "type": string;
    "target": string;
    "is_forgotten": boolean;

    /** Creates a new MemoryListQuery instance. */
    constructor($$source: Partial<MemoryListQuery> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("is_forgotten" in $$source)) {
            this["is_forgotten"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryListQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryListQuery {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryListQuery($$parsedSource as Partial<MemoryListQuery>);
    }
}

export class MemoryListResponse {
    "memories": Memory[];
    "total": number;

    /** Creates a new MemoryListResponse instance. */
    constructor($$source: Partial<MemoryListResponse> = {}) {
        if (!("memories" in $$source)) {
            this["memories"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryListResponse {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("memories" in $$parsedSource) {
            $$parsedSource["memories"] = $$createField0_0($$parsedSource["memories"]);
        }
        return new MemoryListResponse($$parsedSource as Partial<MemoryListResponse>);
    }
}

export class MemoryStats {
    "total": number;
    "week_new": number;
    "forgotten": number;

    /** Creates a new MemoryStats instance. */
    constructor($$source: Partial<MemoryStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("week_new" in $$source)) {
            this["week_new"] = 0;
        }
        if (!("forgotten" in $$source)) {
            this["forgotten"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryStats($$parsedSource as Partial<MemoryStats>);
    }
}

export class MemoryUpdateInput {
    "summary": string;
    "content": string;
    "type": string;
    "target": string;

    /** Creates a new MemoryUpdateInput instance. */
    constructor($$source: Partial<MemoryUpdateInput> = {}) {
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryUpdateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryUpdateInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryUpdateInput($$parsedSource as Partial<MemoryUpdateInput>);
    }
}

export const Message = data_models$0.Message;
export type Message = data_models$0.Message;

export class MessageList {
    "messages": Message[];
    "total": number;

    /** Creates a new MessageList instance. */
    constructor($$source: Partial<MessageList> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageList instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageList {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new MessageList($$parsedSource as Partial<MessageList>);
    }
}

export class Model {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方id
     */
    "provider_id": number;
    "provider_name": string;
    "provider_type": data_models$0.ProviderType;
    "model": string;
    "owned_by": string;
    "object": string;
    "enable": boolean;
    "alias": string | null;
    "is_custom": boolean;

    /** Creates a new Model instance. */
    constructor($$source: Partial<Model> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_id" in $$source)) {
            this["provider_id"] = 0;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("owned_by" in $$source)) {
            this["owned_by"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("alias" in $$source)) {
            this["alias"] = null;
        }
        if (!("is_custom" in $$source)) {
            this["is_custom"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Model instance from a string or object.
     */
    static createFrom($$source: any = {}): Model {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Model($$parsedSource as Partial<Model>);
    }
}

/**
 * OPCCompletionInput 人员私聊输入
 */
export class OPCCompletionInput {
    "chat_uuid": string;
    "person_uuid": string;
    "content": string;
    "model_id": number;
    "model_name": string;

    /** Creates a new OPCCompletionInput instance. */
    constructor($$source: Partial<OPCCompletionInput> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("person_uuid" in $$source)) {
            this["person_uuid"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("model_id" in $$source)) {
            this["model_id"] = 0;
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCCompletionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCCompletionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPCCompletionInput($$parsedSource as Partial<OPCCompletionInput>);
    }
}

/**
 * OPCGroupCompletionInput 群聊输入
 */
export class OPCGroupCompletionInput {
    "chat_uuid": string;
    "group_uuid": string;
    "content": string;
    "model_id": number;
    "model_name": string;

    /** Creates a new OPCGroupCompletionInput instance. */
    constructor($$source: Partial<OPCGroupCompletionInput> = {}) {
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("group_uuid" in $$source)) {
            this["group_uuid"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("model_id" in $$source)) {
            this["model_id"] = 0;
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCGroupCompletionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCGroupCompletionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPCGroupCompletionInput($$parsedSource as Partial<OPCGroupCompletionInput>);
    }
}

/**
 * OPCGroupInput 创建/更新群组的输入
 */
export class OPCGroupInput {
    "uuid": string;
    "name": string;
    "description": string;
    "member_uuids": string[];

    /** Creates a new OPCGroupInput instance. */
    constructor($$source: Partial<OPCGroupInput> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("member_uuids" in $$source)) {
            this["member_uuids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCGroupInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCGroupInput {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("member_uuids" in $$parsedSource) {
            $$parsedSource["member_uuids"] = $$createField3_0($$parsedSource["member_uuids"]);
        }
        return new OPCGroupInput($$parsedSource as Partial<OPCGroupInput>);
    }
}

/**
 * OPCGroupView 群组视图（含成员和最后消息摘要）
 */
export class OPCGroupView {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "uuid": string;
    "chat_uuid": string;
    "name": string;
    "description": string;
    "is_pinned": boolean;
    "members": OPCPersonView[];
    "last_message": string | null;
    "last_message_at": time$0.Time | null;

    /** Creates a new OPCGroupView instance. */
    constructor($$source: Partial<OPCGroupView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("is_pinned" in $$source)) {
            this["is_pinned"] = false;
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }
        if (!("last_message" in $$source)) {
            this["last_message"] = null;
        }
        if (!("last_message_at" in $$source)) {
            this["last_message_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCGroupView instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCGroupView {
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField9_0($$parsedSource["members"]);
        }
        return new OPCGroupView($$parsedSource as Partial<OPCGroupView>);
    }
}

/**
 * OPCPersonInput 创建/更新人员的输入
 */
export class OPCPersonInput {
    "uuid": string;
    "name": string;
    "role": string;
    "prompt": string;
    "tools": string[];
    "skills": string[];
    "avatar": string;

    /** Creates a new OPCPersonInput instance. */
    constructor($$source: Partial<OPCPersonInput> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("prompt" in $$source)) {
            this["prompt"] = "";
        }
        if (!("tools" in $$source)) {
            this["tools"] = [];
        }
        if (!("skills" in $$source)) {
            this["skills"] = [];
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCPersonInput instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCPersonInput {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField4_0($$parsedSource["tools"]);
        }
        if ("skills" in $$parsedSource) {
            $$parsedSource["skills"] = $$createField5_0($$parsedSource["skills"]);
        }
        return new OPCPersonInput($$parsedSource as Partial<OPCPersonInput>);
    }
}

/**
 * OPCPersonView 人员视图（含最后消息摘要）
 */
export class OPCPersonView {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;
    "uuid": string;
    "name": string;
    "role": string;
    "agent_id": string;
    "avatar": string;
    "is_pinned": boolean;
    "chat_uuid": string;
    "last_message": string | null;
    "last_message_at": time$0.Time | null;

    /** Creates a new OPCPersonView instance. */
    constructor($$source: Partial<OPCPersonView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("agent_id" in $$source)) {
            this["agent_id"] = "";
        }
        if (!("avatar" in $$source)) {
            this["avatar"] = "";
        }
        if (!("is_pinned" in $$source)) {
            this["is_pinned"] = false;
        }
        if (!("chat_uuid" in $$source)) {
            this["chat_uuid"] = "";
        }
        if (!("last_message" in $$source)) {
            this["last_message"] = null;
        }
        if (!("last_message_at" in $$source)) {
            this["last_message_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OPCPersonView instance from a string or object.
     */
    static createFrom($$source: any = {}): OPCPersonView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OPCPersonView($$parsedSource as Partial<OPCPersonView>);
    }
}

export class PromptFileDetail {
    "name": string;
    "title": string;
    "description": string;
    "is_system": boolean;
    "content": string;
    "updated_at": time$0.Time | null;

    /** Creates a new PromptFileDetail instance. */
    constructor($$source: Partial<PromptFileDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptFileDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptFileDetail {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptFileDetail($$parsedSource as Partial<PromptFileDetail>);
    }
}

export class PromptFileSummary {
    "name": string;
    "title": string;
    "description": string;
    "is_system": boolean;
    "updated_at": time$0.Time | null;

    /** Creates a new PromptFileSummary instance. */
    constructor($$source: Partial<PromptFileSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("is_system" in $$source)) {
            this["is_system"] = false;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PromptFileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): PromptFileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PromptFileSummary($$parsedSource as Partial<PromptFileSummary>);
    }
}

export class Provider {
    "id": number;
    "created_at": time$0.Time;
    "updated_at": time$0.Time;
    "deleted_at": gorm$0.DeletedAt;

    /**
     * 提供方名称
     */
    "provider_name": string;

    /**
     * 基础url
     */
    "base_url": string;

    /**
     * 文件上传url
     */
    "file_upload_base_url": string | null;

    /**
     * api key
     */
    "api_key": string;

    /**
     * 启用
     */
    "enable": boolean;

    /**
     * 默认供应商
     */
    "is_default": boolean;
    "default_model_id": number | null;
    "models": Model[];
    "custom_models": data_models$0.Model[];
    "provider_type": data_models$0.ProviderType;

    /** Creates a new Provider instance. */
    constructor($$source: Partial<Provider> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = null;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = null;
        }
        if (!("deleted_at" in $$source)) {
            this["deleted_at"] = null;
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }
        if (!("enable" in $$source)) {
            this["enable"] = false;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("default_model_id" in $$source)) {
            this["default_model_id"] = null;
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("custom_models" in $$source)) {
            this["custom_models"] = [];
        }
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provider instance from a string or object.
     */
    static createFrom($$source: any = {}): Provider {
        const $$createField11_0 = $$createType12;
        const $$createField12_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField11_0($$parsedSource["models"]);
        }
        if ("custom_models" in $$parsedSource) {
            $$parsedSource["custom_models"] = $$createField12_0($$parsedSource["custom_models"]);
        }
        return new Provider($$parsedSource as Partial<Provider>);
    }
}

export class SkillDetail {
    "name": string;
    "description": string;
    "when": string;
    "version": string;
    "tags": string[];
    "content": string;

    /** Creates a new SkillDetail instance. */
    constructor($$source: Partial<SkillDetail> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("when" in $$source)) {
            this["when"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillDetail {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new SkillDetail($$parsedSource as Partial<SkillDetail>);
    }
}

export class SkillSummary {
    "name": string;
    "description": string;
    "when": string;
    "version": string;
    "tags": string[];

    /** Creates a new SkillSummary instance. */
    constructor($$source: Partial<SkillSummary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("when" in $$source)) {
            this["when"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillSummary {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new SkillSummary($$parsedSource as Partial<SkillSummary>);
    }
}

export class SupportProvider {
    "provider_type": data_models$0.ProviderType;
    "icon": string;
    "name": string;
    "base_url": string;
    "file_upload_base_url": string | null;
    "description": string;

    /** Creates a new SupportProvider instance. */
    constructor($$source: Partial<SupportProvider> = {}) {
        if (!("provider_type" in $$source)) {
            this["provider_type"] = data_models$0.ProviderType.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("base_url" in $$source)) {
            this["base_url"] = "";
        }
        if (!("file_upload_base_url" in $$source)) {
            this["file_upload_base_url"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SupportProvider instance from a string or object.
     */
    static createFrom($$source: any = {}): SupportProvider {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SupportProvider($$parsedSource as Partial<SupportProvider>);
    }
}

export const Task = data_models$0.Task;
export type Task = data_models$0.Task;

export class TaskList {
    "tasks": Task[];

    /** Creates a new TaskList instance. */
    constructor($$source: Partial<TaskList> = {}) {
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskList instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskList {
        const $$createField0_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        return new TaskList($$parsedSource as Partial<TaskList>);
    }
}

export class Tool {
    "id": string;
    "name": string;
    "description": string;
    "source_type": string;
    "enabled": boolean;
    "is_deletable": boolean;
    "plugin_type"?: string;
    "use_tools"?: plugins$0.PluginTool[];
    "view_tools"?: plugins$0.PluginTool[];
    "agents"?: plugins$0.PluginAgent[];

    /** Creates a new Tool instance. */
    constructor($$source: Partial<Tool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("is_deletable" in $$source)) {
            this["is_deletable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tool instance from a string or object.
     */
    static createFrom($$source: any = {}): Tool {
        const $$createField7_0 = $$createType18;
        const $$createField8_0 = $$createType18;
        const $$createField9_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("use_tools" in $$parsedSource) {
            $$parsedSource["use_tools"] = $$createField7_0($$parsedSource["use_tools"]);
        }
        if ("view_tools" in $$parsedSource) {
            $$parsedSource["view_tools"] = $$createField8_0($$parsedSource["view_tools"]);
        }
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField9_0($$parsedSource["agents"]);
        }
        return new Tool($$parsedSource as Partial<Tool>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AgentPrompt.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = data_models$0.Chat.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Memory.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = data_models$0.Message.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = OPCPersonView.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Model.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = data_models$0.Model.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = data_models$0.Task.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = plugins$0.PluginTool.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = plugins$0.PluginAgent.createFrom;
const $$createType20 = $Create.Array($$createType19);
