// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PluginAgent {
    "id": string;
    "name": string;
    "description": string;

    /** Creates a new PluginAgent instance. */
    constructor($$source: Partial<PluginAgent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginAgent instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginAgent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginAgent($$parsedSource as Partial<PluginAgent>);
    }
}

export class PluginTool {
    "id": string;
    "name": string;
    "description": string;
    "inputSchema": { [_ in string]?: any };
    "viewId": string;
    "requireConfirmation": boolean;

    /** Creates a new PluginTool instance. */
    constructor($$source: Partial<PluginTool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("inputSchema" in $$source)) {
            this["inputSchema"] = {};
        }
        if (!("viewId" in $$source)) {
            this["viewId"] = "";
        }
        if (!("requireConfirmation" in $$source)) {
            this["requireConfirmation"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginTool instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginTool {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputSchema" in $$parsedSource) {
            $$parsedSource["inputSchema"] = $$createField3_0($$parsedSource["inputSchema"]);
        }
        return new PluginTool($$parsedSource as Partial<PluginTool>);
    }
}

export class PluginView {
    "id": string;
    "name": string;
    "entry": string;

    /** Creates a new PluginView instance. */
    constructor($$source: Partial<PluginView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("entry" in $$source)) {
            this["entry"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginView instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginView($$parsedSource as Partial<PluginView>);
    }
}

export class RuntimeStatus {
    "available": boolean;
    "runtime_path": string;
    "node_path": string;
    "version": string;
    "download_url": string;
    "error": string;
    "downloading": boolean;
    "progress": number;
    "downloaded_bytes": number;
    "total_bytes": number;
    "phase": string;

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("runtime_path" in $$source)) {
            this["runtime_path"] = "";
        }
        if (!("node_path" in $$source)) {
            this["node_path"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("download_url" in $$source)) {
            this["download_url"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("downloading" in $$source)) {
            this["downloading"] = false;
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("downloaded_bytes" in $$source)) {
            this["downloaded_bytes"] = 0;
        }
        if (!("total_bytes" in $$source)) {
            this["total_bytes"] = 0;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}

export class Summary {
    "id": string;
    "name": string;
    "version": string;
    "description": string;
    "type": string;
    "author": string;
    "enabled": boolean;
    "status": string;
    "last_error": string;
    "has_settings": boolean;
    "permissions": string[];
    "use_tools": PluginTool[];
    "view_tools": PluginTool[];
    "agents": PluginAgent[];
    "views": PluginView[];
    "hooks": string[];

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("last_error" in $$source)) {
            this["last_error"] = "";
        }
        if (!("has_settings" in $$source)) {
            this["has_settings"] = false;
        }
        if (!("permissions" in $$source)) {
            this["permissions"] = [];
        }
        if (!("use_tools" in $$source)) {
            this["use_tools"] = [];
        }
        if (!("view_tools" in $$source)) {
            this["view_tools"] = [];
        }
        if (!("agents" in $$source)) {
            this["agents"] = [];
        }
        if (!("views" in $$source)) {
            this["views"] = [];
        }
        if (!("hooks" in $$source)) {
            this["hooks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType3;
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField10_0($$parsedSource["permissions"]);
        }
        if ("use_tools" in $$parsedSource) {
            $$parsedSource["use_tools"] = $$createField11_0($$parsedSource["use_tools"]);
        }
        if ("view_tools" in $$parsedSource) {
            $$parsedSource["view_tools"] = $$createField12_0($$parsedSource["view_tools"]);
        }
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField13_0($$parsedSource["agents"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField14_0($$parsedSource["views"]);
        }
        if ("hooks" in $$parsedSource) {
            $$parsedSource["hooks"] = $$createField15_0($$parsedSource["hooks"]);
        }
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = PluginTool.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PluginAgent.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PluginView.createFrom;
const $$createType7 = $Create.Array($$createType6);
