// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings manages config persistence and file-system level settings actions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings_dto$0 from "./settings_dto/models.js";

/**
 * ApplyFileSettings migrates config and database artifacts into a new data directory and updates the locator file.
 */
export function ApplyFileSettings(input: settings_dto$0.ApplyFileSettingsInput): $CancellablePromise<settings_dto$0.ApplyFileSettingsOutput | null> {
    return $Call.ByID(958200195, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LoadBootstrap loads the config file and provider list required by the settings frontend entry.
 */
export function LoadBootstrap(input: settings_dto$0.LoadBootstrapInput): $CancellablePromise<settings_dto$0.LoadBootstrapOutput | null> {
    return $Call.ByID(4078124534, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveDisplaySettings updates the persisted application font-size preference.
 */
export function SaveDisplaySettings(input: settings_dto$0.SaveDisplaySettingsInput): $CancellablePromise<settings_dto$0.SaveDisplaySettingsOutput | null> {
    return $Call.ByID(1981453932, input).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SaveLocaleSettings updates locale and language in the persisted config file.
 */
export function SaveLocaleSettings(input: settings_dto$0.SaveLocaleSettingsInput): $CancellablePromise<settings_dto$0.SaveLocaleSettingsOutput | null> {
    return $Call.ByID(3195924422, input).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveShortcutSettings persists and immediately applies the quick chat shortcut.
 */
export function SaveShortcutSettings(input: settings_dto$0.SaveShortcutSettingsInput): $CancellablePromise<settings_dto$0.SaveShortcutSettingsOutput | null> {
    return $Call.ByID(1452815738, input).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ValidateShortcutSettings checks whether a quick chat shortcut can be used.
 */
export function ValidateShortcutSettings(input: settings_dto$0.ValidateShortcutSettingsInput): $CancellablePromise<settings_dto$0.ValidateShortcutSettingsOutput | null> {
    return $Call.ByID(2696595609, input).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = settings_dto$0.ApplyFileSettingsOutput.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = settings_dto$0.LoadBootstrapOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = settings_dto$0.SaveDisplaySettingsOutput.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = settings_dto$0.SaveLocaleSettingsOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = settings_dto$0.SaveShortcutSettingsOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = settings_dto$0.ValidateShortcutSettingsOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
